### PR TITLE
Add support 4g in EngineerMode

### PR DESCRIPTION
**Pull request by gfofanov**
ro.mtk_lte_support=1
[system.prop.zip](https://github.com/MediatekAndroidDevelopers/android_device_jiayu_s3_h560/files/1633846/system.prop.zip)

### CODE REVIEW

**Comment by iMiKED** [comment]
wtf is this, @gfofanov?)

**Comment by DerTeufel** [comment]
That's what I thought as well @iMiKED

**Comment by ghost** [comment]
lol )

**Comment by dragonpt** [comment]
We should merge this :p 

;) hah

**Pull request closed without merging**
